unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

set -g status-style "bg=#262a2b,fg=#ebdbb2"

set -g status-left-style "bg=#3c3836,fg=#ebdbb2"
set -g status-right-style "bg=#3c3836,fg=#ebdbb2"

setw -g window-status-style "bg=#262a2b,fg=#928374"
setw -g window-status-current-style "bg=#504945,fg=#ebdbb2"
set -g status-right-length 100

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'tmux-revamped/tmux-music-revamped'
set -g @music_revamped_max_len 30
set -g @music_revamped_format "%s - %s"

set -g status-right '"#H" %H:%M %d-%b-%y #{music_icon} #{music}'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

